/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dfmDrone.gui;

import dfmDrone.ai.CommandQueue;

/**
 *
 * @author Signe
 */
public class ManualPanel extends javax.swing.JPanel {

    private final GUIController controller;
    
    /**
     * Creates new form ManualPanel
     */
    public ManualPanel(GUIController controller) {
        
        this.controller = controller;
        
        initComponents();
    }

    
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Up = new javax.swing.JButton();
        Left = new javax.swing.JButton();
        Down = new javax.swing.JButton();
        Right = new javax.swing.JButton();
        rotateL = new javax.swing.JButton();
        rotateR = new javax.swing.JButton();
        Forward = new javax.swing.JButton();
        Reverse = new javax.swing.JButton();

        Up.setText("Up");
        Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpActionPerformed(evt);
            }
        });

        Left.setText("Left");
        Left.setActionCommand("left");
        Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftActionPerformed(evt);
            }
        });

        Down.setText("Down");
        Down.setActionCommand("down");
        Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownActionPerformed(evt);
            }
        });

        Right.setText("Right");
        Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightActionPerformed(evt);
            }
        });

        rotateL.setText("Rotate Left");
        rotateL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateLActionPerformed(evt);
            }
        });

        rotateR.setText("Rotate Right");
        rotateR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateRActionPerformed(evt);
            }
        });

        Forward.setText("Forward");
        Forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardActionPerformed(evt);
            }
        });

        Reverse.setText("Reverse");
        Reverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReverseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Reverse)
                    .addComponent(Forward)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Left)
                            .addComponent(rotateL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Right)
                    .addComponent(rotateR))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(Forward)
                .addGap(18, 18, 18)
                .addComponent(Reverse)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Up)
                    .addComponent(rotateL)
                    .addComponent(rotateR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Right)
                    .addComponent(Left)
                    .addComponent(Down))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardActionPerformed
        controller.cmdQ.add(CommandQueue.Command.Forward, 15, 250, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_ForwardActionPerformed

    private void ReverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReverseActionPerformed
       controller.cmdQ.add(CommandQueue.Command.Backward, 15, 250, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_ReverseActionPerformed

    private void rotateLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateLActionPerformed
        controller.cmdQ.add(CommandQueue.Command.SpinLeft, 30, 500, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_rotateLActionPerformed

    private void UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpActionPerformed
        controller.cmdQ.add(CommandQueue.Command.MoveUp, 15, 250, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_UpActionPerformed

    private void rotateRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateRActionPerformed
        controller.cmdQ.add(CommandQueue.Command.SpinRight, 30, 500, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_rotateRActionPerformed

    private void LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftActionPerformed
        controller.cmdQ.add(CommandQueue.Command.MoveLeft, 15, 250, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_LeftActionPerformed

    private void DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownActionPerformed
        controller.cmdQ.add(CommandQueue.Command.MoveDown, 15, 250, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_DownActionPerformed

    private void RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightActionPerformed
        controller.cmdQ.add(CommandQueue.Command.MoveRight, 15, 250, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_RightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Down;
    private javax.swing.JButton Forward;
    private javax.swing.JButton Left;
    private javax.swing.JButton Reverse;
    private javax.swing.JButton Right;
    private javax.swing.JButton Up;
    private javax.swing.JButton rotateL;
    private javax.swing.JButton rotateR;
    // End of variables declaration//GEN-END:variables
}
