package dfmDrone.gui;

import dfmDrone.ai.CommandQueue;
import java.awt.event.KeyEvent;

/**
 * @author Mathias & Frank
 */
public class ManualPanel extends javax.swing.JPanel
{
    private final Controller controller;
    
    /**
     * Creates new form ManualPanel
     * @param controller
     */
    public ManualPanel(Controller controller) {
        this.controller = controller;
        
        initComponents();
        this.setFocusable(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Up = new javax.swing.JButton();
        Left = new javax.swing.JButton();
        Down = new javax.swing.JButton();
        Right = new javax.swing.JButton();
        rotateL = new javax.swing.JButton();
        rotateR = new javax.swing.JButton();
        Forward = new javax.swing.JButton();
        Reverse = new javax.swing.JButton();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        Up.setText("Up");
        Up.setFocusable(false);
        Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpActionPerformed(evt);
            }
        });

        Left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfmDrone/gui/symbols/left_24.png"))); // NOI18N
        Left.setActionCommand("left");
        Left.setFocusable(false);
        Left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftActionPerformed(evt);
            }
        });

        Down.setText("Down");
        Down.setActionCommand("down");
        Down.setFocusable(false);
        Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownActionPerformed(evt);
            }
        });

        Right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfmDrone/gui/symbols/right_24.png"))); // NOI18N
        Right.setFocusable(false);
        Right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightActionPerformed(evt);
            }
        });

        rotateL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfmDrone/gui/symbols/rotate_left_24.png"))); // NOI18N
        rotateL.setFocusable(false);
        rotateL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateLActionPerformed(evt);
            }
        });

        rotateR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfmDrone/gui/symbols/rotate_right_24.png"))); // NOI18N
        rotateR.setFocusable(false);
        rotateR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateRActionPerformed(evt);
            }
        });

        Forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfmDrone/gui/symbols/up_24.png"))); // NOI18N
        Forward.setFocusable(false);
        Forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForwardActionPerformed(evt);
            }
        });

        Reverse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dfmDrone/gui/symbols/down_24.png"))); // NOI18N
        Reverse.setFocusable(false);
        Reverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReverseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotateL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Reverse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Forward)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotateR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Down, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Down, Forward, Left, Reverse, Right, Up, rotateL, rotateR});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Up)
                            .addComponent(Down))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotateL)
                            .addComponent(rotateR)))
                    .addComponent(Forward))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Left)
                        .addComponent(Right, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(Reverse, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForwardActionPerformed
        controller.cmdQ.add(CommandQueue.Command.Forward, 15, 500, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_ForwardActionPerformed

    private void ReverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReverseActionPerformed
       controller.cmdQ.add(CommandQueue.Command.Backward, 15, 500, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_ReverseActionPerformed

    private void rotateLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateLActionPerformed
        controller.cmdQ.add(CommandQueue.Command.SpinLeft, 20, 500, CommandQueue.PushType.Instant, CommandQueue.PushType.IgnoreBusy);
    }//GEN-LAST:event_rotateLActionPerformed

    private void UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpActionPerformed
        controller.cmdQ.add(CommandQueue.Command.MoveUp, 15, 500, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_UpActionPerformed

    private void rotateRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateRActionPerformed
        controller.cmdQ.add(CommandQueue.Command.SpinRight, 20, 500, CommandQueue.PushType.Instant, CommandQueue.PushType.IgnoreBusy);
    }//GEN-LAST:event_rotateRActionPerformed

    private void LeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftActionPerformed
        controller.cmdQ.add(CommandQueue.Command.MoveLeft, 15, 250, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_LeftActionPerformed

    private void DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownActionPerformed
        controller.cmdQ.add(CommandQueue.Command.MoveDown, 15, 500, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_DownActionPerformed

    private void RightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightActionPerformed
        controller.cmdQ.add(CommandQueue.Command.MoveRight, 15, 250, CommandQueue.PushType.Instant);
    }//GEN-LAST:event_RightActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch(evt.getKeyCode()) {
            case KeyEvent.VK_W: { //Forward
                ForwardActionPerformed(null); break;
            }
            case KeyEvent.VK_S: { //Back
                ReverseActionPerformed(null); break;
            }
            case KeyEvent.VK_A: { //Left
                LeftActionPerformed(null); break;
            }
            case KeyEvent.VK_D: { //Right
                RightActionPerformed(null); break;
            }
            case KeyEvent.VK_Q: { //Rotate Left
                rotateLActionPerformed(null); break;
            }
            case KeyEvent.VK_E: { //Rotate Right
                rotateRActionPerformed(null); break;
            }
            case KeyEvent.VK_CONTROL: { //Down
                DownActionPerformed(null); break;
            }
            case KeyEvent.VK_SPACE: { //Up
                UpActionPerformed(null); break;
            }
        }
    }//GEN-LAST:event_formKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Down;
    private javax.swing.JButton Forward;
    private javax.swing.JButton Left;
    private javax.swing.JButton Reverse;
    private javax.swing.JButton Right;
    private javax.swing.JButton Up;
    private javax.swing.JButton rotateL;
    private javax.swing.JButton rotateR;
    // End of variables declaration//GEN-END:variables
}